# Generated by Django 4.0.1 on 2022-01-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifyapi', '0002_alter_referrals_referral_code_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
