# Generated by Django 4.0.1 on 2022-01-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifyapi', '0004_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
