# Generated by Django 4.0.1 on 2022-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifyapi', '0005_remove_userdata_user_userdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='email',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
