# Generated by Django 4.0.1 on 2022-01-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifyapi', '0006_referrals_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_number', models.TextField()),
                ('event_code', models.TextField()),
                ('participant_id', models.TextField()),
                ('participant_name', models.TextField()),
                ('certificate_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.TextField()),
                ('uid_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.TextField()),
                ('event_code', models.TextField()),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
