# Generated by Django 4.0.1 on 2022-01-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifyapi', '0008_rename_content_events_certificate_default_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='template_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
