# Generated by Django 4.0.1 on 2022-01-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifyapi', '0009_events_template_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='date_issued',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
