# Generated by Django 4.0.1 on 2022-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifyapi', '0010_certificates_date_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='content',
            field=models.TextField(default='Normal Certificate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificates',
            name='position',
            field=models.TextField(null=True),
        ),
    ]
